# The URL the site will be built for
base_url = "https://aheyler.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false
theme = "papaya"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
highlight_themes_css = [ƒ
  { theme = "material-dark", filename = "syntax-theme-dark.css" },
  { theme = "material-light", filename = "syntax-theme-light.css" },
]

[extra]
# Put all your custom variables here
# Development environment. Used by the page macros to load remote content only when in "prod" mode
env = "ZOLA_ENV"
# Color theme mode. Options: light, dark, auto (automatically switch depending on OS/user agent settings)
color_mode = "auto"

# List of Papaya navigational menu items. Used to construct the navigation bar. See the README for item schema.
menu_items = [
    { name = "home", url = "$LANG_BASE_URL/", show_recent = false },
    { name = "experience", url = "$LANG_BASE_URL/experience", show_recent = false },
    { name = "projects", url = "$LANG_BASE_URL/projects", show_recent = false },
    #{ name = "projects_list", url = "$LANG_BASE_URL/projects_list", show_recent = true, recent_items = 3, recent_trans_key = "recent_projects", more_trans_key = "more_projects" },
    #{ name = "blog", url = "$LANG_BASE_URL/blog", show_recent = true, recent_items = 3, recent_trans_key = "recent_blog_posts", more_trans_key = "more_blog_posts" },
    # tag is not a zola section, it's just a link.
    #{ name = "tags", url = "$LANG_BASE_URL/tags" },
]


[languages]

[languages.en]
title = "Angelina Heyler"
description = ""
generate_feeds = true
generate_feed = true
feed_filename = "atom.xml"
# The taxonomies to be rendered for the site and their configuration of the default languages
taxonomies = [
    { name = "tags", feed = true, lang = "en" },
    { name = "categories", feed = true, lang = "en" },
]

[languages.en.translations]
projects = "Projects"
blog = "Blog"
about = "About"
experience = "Experience"
home = "Home"
recent_projects = "Recent Projects"
more_projects = "More Projects"
recent_blog_posts = "Recent Blog Posts"
more_blog_posts = "More blog posts"
tag = "Tag"
tags = "Tags"
to_all_tags = "To all tags"
category = "Category"
categories = "Categories"
to_all_categories = "To all categories"
view_by = "View by"
other = "Other"
minute = "min"
prev_page = "To newer posts"
next_page = "To older posts"
# Customize your post date format. See: https://tera.netlify.app/docs/#date
date_format = "%B %e, %Y"

[extra.images]
# Width defined in pixels
max_width = 2500

[extra.social]
email = "angelinaheyler@gmail.com"
github = "aheyler"
linkedin = "angelina-heyler"

[extra.cdn]
font_awesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css"

[extra.ogp]
first_name = "Angelina" 
last_name = "Heyler"
locale = "en_US"
gender = ""
username = ""